# Generated by Django 6.0.1 on 2026-03-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bouquet_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/bouquets/'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            field=models.CharField(blank=True, db_index=True, max_length=12, unique=True),
        ),
    ]
