# Generated by Django 6.0.1 on 2026-03-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_tracking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/items/'),
        ),
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
