# Generated by Django 6.0.1 on 2026-03-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_item_image_order_item_name_order_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
