# Generated by Django 6.0.1 on 2026-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
