# Generated by Django 6.0.1 on 2026-02-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.bouquetsize')),
            ],
        ),
        migrations.CreateModel(
            name='BouquetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('scale', models.FloatField(default=1.0)),
                ('rotation', models.FloatField(default=0.0)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bouquet.bouquet')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.flower')),
            ],
        ),
    ]
