# Generated by Django 6.0.1 on 2026-03-05 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_predesignedbouquet_flower_stock_service_is_active_and_more'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('global', 'Global (Toda la tienda)'), ('category', 'Por Categoría de Flor'), ('product', 'Por Flor Específica')], default='global', max_length=10)),
                ('tier_target', models.CharField(blank=True, choices=[('l', 'Grande'), ('m', 'Mediana'), ('s', 'Pequeña')], max_length=1, null=True)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('flower_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.flower')),
            ],
        ),
    ]
