# Generated by Django 6.0.1 on 2026-03-08 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_predesignedbouquet_size'),
        ('discounts', '0002_alter_coupon_discount_percentage_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='bouquet_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.predesignedbouquet', verbose_name='Ramo Objetivo'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: 5.00 para descontar 5 dólares exactos.', max_digits=10, verbose_name='Monto Fijo ($)'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='flower_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.flower', verbose_name='Flor Objetivo'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está activo'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Descuento'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.PositiveIntegerField(default=0, help_text='Ej: 15 para un 15 por ciento de descuento.', verbose_name='Porcentaje (%)'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='tier_target',
            field=models.CharField(blank=True, choices=[('l', 'Grande'), ('m', 'Mediana'), ('s', 'Pequeña')], max_length=1, null=True, verbose_name='Categoría Objetivo'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('global', 'Global (Toda la tienda)'), ('category', 'Por Categoría de Flor'), ('product', 'Por Flor Específica'), ('bouquet', 'Por Ramo Específico')], default='global', max_length=10, verbose_name='Tipo de Aplicación'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Válido desde'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Válido hasta'),
        ),
    ]
