# Generated by Django 6.0.1 on 2026-03-08 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_predesignedbouquet_size'),
        ('discounts', '0003_discount_bouquet_target_alter_discount_fixed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='promotion_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.promotion', verbose_name='Promoción Objetivo'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('global', 'Global (Toda la tienda)'), ('category', 'Por Categoría de Flor'), ('product', 'Por Flor Específica'), ('bouquet', 'Por Ramo Específico'), ('promotion', 'Por Promoción Específica')], default='global', max_length=10, verbose_name='Tipo de Aplicación'),
        ),
    ]
