# Generated by Django 6.0.1 on 2026-03-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_service_image_icon_service_image_and_more'),
        ('discounts', '0004_discount_promotion_target_alter_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='service_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.service', verbose_name='Servicio Objetivo'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('global', 'Global (Toda la tienda)'), ('category', 'Por Categoría de Flor'), ('product', 'Por Flor Específica'), ('bouquet', 'Por Ramo Específico'), ('promotion', 'Por Promoción Específica'), ('service', 'Por Servicio Específico')], default='global', max_length=10, verbose_name='Tipo de Aplicación'),
        ),
    ]
