# Generated by Django 6.0.1 on 2026-02-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.SlugField(unique=True)),
                ('max_large', models.PositiveIntegerField(default=0)),
                ('max_medium', models.PositiveIntegerField(default=0)),
                ('max_small', models.PositiveIntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('l', 'Grande'), ('m', 'Mediana'), ('s', 'Pequeña')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='flowers/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='flowers/thumbs/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
