# Generated by Django 6.0.1 on 2026-03-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_predesignedbouquet_flower_stock_service_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji o clase de icono (ej: 🧸, 💬)', max_length=50, null=True),
        ),
    ]
