# Generated by Django 6.0.1 on 2026-03-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_portfolioitem_remove_service_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
