# Generated by Django 6.0.1 on 2026-03-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_icon',
            field=models.ImageField(blank=True, help_text='Imagen 3D o personaliza para el servicio', null=True, upload_to='service_icons/'),
        ),
    ]
