# Generated by Django 6.0.1 on 2026-03-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_service_image_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='predesignedbouquet',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predesigned_bouquets', to='catalog.bouquetsize'),
        ),
    ]
